### ISSUE TITLE
TO-DO LIST

### ISSUE THREAD

**Issue by cok2exe** [cok2exe/chat#1]
... 20.01.12
- [ ] 여러개의 채팅방 만들 수 있게 수정하기
- [ ] join, leave 사용해보기
- [ ] 라우트 쪼개기
- [ ] /components 폴더에는 UI 요소들만, /containers 에 페이지 구조
- [ ] Semantic UI (또는 그 외 다른 것들) 적용하기 (나는 디자인이 구리다)

**Comment by shinbi-park** [comment]
20년도 ㄷㄷ
